@startuml PIIProyecto2025

' Paquete principal
package "Dominio" {
    
    class Program {
        - mapa: Mapa
        - jugadores: List<Jugador>
        - turnoActual: int
        + iniciarJuego()
        + avanzarTurno()
        + obtenerEstado()
    }

    class Jugador{
        - nombre: String
        - civilizacion: Civilizacion
        - recursos: Recursos
        - aldeanos: List<Aldeano>
        - edificios: List<Edificio>
        - unidades: List<UnidadMilitar>
        + recolectarRecurso(tipo: TipoRecurso, ubicacion: Coordenada)
        + construir(edificio: Edificio, ubicacion: Coordenada)
        + entrenarUnidad(tipo: TipoUnidad)
        + moverUnidad(idUnidad: int, destino: Coordenada)
        + atacar(idAtacante: int, objetivo: Coordenada)
        + accesible: boolean
        + info()
    }

    class Mapa {
        - tamaño: int
        - celdas: List<Celda>
        + obtenerCelda(coordenada: Coordenada): Celda
    }

    class Celda{
        - coordenada: Coordenada
        - contenido: List<ElementoMapa>
    }

    class Coordenada {
        - x: int
        - y: int
    }

    interface IRecurso {
        - tipo: TipoRecurso
        - cantidad: int
        - tasaRecoleccion: int
        + mover(coordenada: Coordenada) : edificio
        + agregar(tipo: TipoRecurso, cantidad: int)
        + consumir(tipo: TipoRecurso, cantidad: int): boolean
        + alerta: boolean 
        
    }

    enum TipoRecurso {
        Alimento
        Madera
        Oro 
        Piedra
    }
    
    abstract class Civilizacion{
        - nombre: List<String>
    
    }
    
    interface IEdificios{
        - nombre: List<String>
        - capacidad: int 
    }
    
    class UnidadMilitar implements IEdificios {
        - tipo: String
        - bonificiacion: int
        - ubicacion: Coordenada
        - cantidad: int
    }

    
    class UnidadCivil implements IEdificios{
        - tipo: String
        - ubicacion: Coordenada
        - cantidad: int
    
    }
    
    class Recursos implements IRecurso {
        - recursos: Map<TipoRecurso, Integer>
        + agregar(tipo: TipoRecurso, cantidad: int)
        + consumir(tipo: TipoRecurso, cantidad: int): boolean
        + mover(...) ...
        + alerta: boolean
    }
    
    abstract class Recurso {
    - tipo: TipoRecurso
    - cantidad: int
    }
       
    class Construir extends Recurso{
    + contarDistancia()
    + mostrarTiempo()    
    }
    
    class Recoleccion extends Recurso{
    - tasaRecoleccion: int
    + contarDistancia()
    }
  
  Program --> Mapa
  Program --> Jugador
  Mapa --> Celda
  Jugador --> Civilizacion
  Jugador --> UnidadMilitar
  Jugador --> UnidadCivil
  Jugador --> Recursos
  Celda --> Coordenada
  UnidadMilitar --> Coordenada
  Construir --> TipoRecurso
  Recoleccion --> TipoRecurso 
}

@enduml
